apiVersion: v1
kind: Service
metadata:
  name: clicker
spec:
  selector:
    app: clicker
    tier: backend
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
  type: ClusterIP