name: Build Backend Image

on:
  push:
    branches:
      - master
      - feat/build-pipelines
    paths:
      - '.github/workflows/**'
      - 'backend/**'
  pull_request:
    branches:
      - master
      - feat/build-pipelines
    paths:
      - '.github/workflows/**'
      - 'backend/**'

env:
  REGISTRY: ghcr.io
  REPO_NAME: ${{ github.repository }}

jobs:
  build-backend:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Get version from package.json
        id: get_version
        run: |
          VERSION=$(jq -r .version backend/package.json)
          echo "IMAGE_VERSION=$VERSION" >> $GITHUB_ENV

      - name: Log in with PAT
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: nocxxy
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Build & Push backend image
        run: |
          IMAGE_NAME=${{ env.REGISTRY }}/${{ env.REPO_NAME }}/backend:${{ env.IMAGE_TAG }}
          docker build -t $IMAGE_NAME ./backend
          docker push $IMAGE_NAME
