name: Build Backend Image

on:
  push:
    branches:
      - master
      - feat/build-pipelines
    paths:
      - '.github/workflows/**'
      - 'backend/**'
  pull_request:
    branches:
      - master
      - feat/build-pipelines
    paths:
      - '.github/workflows/**'
      - 'backend/**'

jobs:
  build-backend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Get version from package.json
        id: get_version
        run: |
          VERSION=$(jq -r .version backend/package.json)
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Build backend image
        run: |
          IMAGE_NAME=ghcr.io/${{ github.repository }}/backend:${{ steps.get_version.outputs.version }}
          docker build -t $IMAGE_NAME ./backend
          docker push $IMAGE_NAME
